version: '3.7'

services:
  my_container:
    image: zrross11/snporacle:1.0.3
    container_name: subnet28-miner
    network_mode: host
    volumes:
      - /home/ubuntu/.bittensor:/root/.bittensor
    restart: always
    command: "python ./neurons/miner.py --wallet.name default --wallet.hotkey default --netuid 28 --axon.port 30334 --subtensor.network local --subtensor.chain_endpoint 127.0.0.1:9944 --logging.debug"
